# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# Environment Properties
# You can find the latest versions here: https://projects.neoforged.net/neoforged/neoforge
# The Minecraft version must agree with the Neo version to get a valid artifact
minecraft_version=1.21.1
# The Minecraft version range can use any release version of Minecraft as bounds.
minecraft_version_range=[1.21.1, 1.22)
# The Neo version must agree with the Minecraft version to get a valid artifact
neo_version=21.1.176
# The Neo version range can use any version of Neo as bounds
neo_version_range=[21.1.0,)
# The loader version range can only be the major version of FML as bounds
loader_version_range=[4,)

## Mod Properties

# The unique mod identifier for the mod. Must be lowercase in English locale. Must fit the regex [a-z][a-z0-9_]{1,63}
mod_id=tankscraft
# The human-readable display name for the mod.
mod_name=TanksCraft
# The license of the mod. Review your options at https://choosealicense.com/.
mod_license=MIT
# The mod version. See https://semver.org/
mod_version=0.1.0
# The group ID for the mod. It is only important when publishing as an artifact to a Maven repository.
mod_group_id=com.tankscraft
# The authors of the mod.
mod_authors=Ninjago21820
# The description of the mod.
mod_description=Le garage World of Tanks remplace le menu principal de Minecraft. Feuilletez votre collection de chars, choisissez votre machine de guerre et partez au combat !
